# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)} {h([{l}])} - {m}{n}"

  # An appender named "rolling" that writes to a rolling file with a custom pattern encoder
  rolling:
    kind: rolling_file
    path: "log/client.log"
    policy:
      roller:
        kind: fixed_window
        pattern: "log/client.log.{}"
        base: 1
        count: 10
      trigger:
        kind: size
        limit: 1 mb
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S %Z)} [{l}] - {m}{n}"

# Set the default logging level to "debug" and attach the "stdout" appender to the root
root:
  level: debug
  appenders:
    - stdout
    - rolling
